### ISSUE TITLE
Please simplify the vimrc and provide the sound control commands

### ISSUE THREAD

**Issue by obo** [ELITR/manual-revision-of-transcripts#1]
I uploaded the vimrc into ``https://github.com/ELITR/manual-revision-of-transcripts/tree/master/on-linux-in-vim`` but when I looked at it and tried it, it did not seem to contain any sound-controlling shortcuts, it only quite substantially changes the default vim environment.

Could you please *reduce* the changes of the environment, so that it is easier for other vim users to use and *add* the sound controlling macros?

Once this is done, please contact Sangeet, co that we can recommend this setup to Adam Dingle revising his talks.

**Comment by jonaskratochvil** [comment]
Hello,

I have modified my .vimrc to contain only the essential things that I use directly for transcript correction, I have also included the audio pause/play shortcuts, which can be modified to suit the individual need. I have updated README with clearer instructions on how I use these inside vim, let me know if further clarification is needed.

**Comment by obo** [comment]
Thanks!

Instead of the jj trick, how about using 'imap' and mapping e.g. F1, F2 for these commands?

Cheers, O.

----- Original Message -----
> From: "jonaskratochvil" <notifications@github.com>
> To: "ELITR/manual-revision-of-transcripts" <manual-revision-of-transcripts@noreply.github.com>
> Cc: "Ondrej Bojar" <bojar@ufal.mff.cuni.cz>, "Author" <author@noreply.github.com>
> Sent: Monday, 25 November, 2019 12:01:22
> Subject: Re: [ELITR/manual-revision-of-transcripts] Please simplify the vimrc and provide the sound control commands
> (#1)

> Hello,
> 
> I have modified my .vimrc to contain only the essential things that I use
> directly for transcript correction, I have also included the audio pause/play
> shortcuts, which can be modified to suit the individual need. I have updated
> README with clearer instructions on how I use these inside vim, let me know if
> further clarification is needed.
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/ELITR/manual-revision-of-transcripts/issues/1#issuecomment-558104326

-- 
Ondrej Bojar (mailto:obo@cuni.cz / bojar@ufal.mff.cuni.cz)
http://www.cuni.cz/~obo
